### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by laktak** [thebinarysearchtree/regexpbuilderjs#6]
Could you add an export and push this to npm?

**Comment by seiyria** [comment]
And bower!

**Comment by rayshan** [comment]
+1

**Comment by mthenw** [comment]
:+1:

**Comment by seiyria** [comment]
So... no?

**Comment by rayshan** [comment]
https://www.npmjs.com/package/regexpbuilder

**Comment by seiyria** [comment]
Ah, my bad, I searched for regexpbuilderjs. Thanks!
